# Generated by Django 5.2.17 on 2026-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "impact",
                    models.CharField(
                        default="Impact estimé à calculer", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planifié"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
